fixbug: interface{} should be generated/typed to 'any'
go-swagger/go-swagger pull request #2776
Opened 2022-05-21 21:57 UTC by emilgpa

```go
package main

// swagger:model Example
type Example struct {
	MyField map[string]interface{} `json:"my_field,omitempty"`
}
```
should to generate:

```
{
  "swagger": "2.0",
  "paths": {},
  "definitions": {
    "Example": {
      "type": "object",
      "properties": {
        "my_field": {
          "type": "object",
          "additionalProperties": {},
          "x-go-name": "MyField"
        }
      }
    }
  }
}
```

but currently generates:

```
{
  "swagger": "2.0",
  "paths": {},
  "definitions": {
    "Example": {
      "type": "object",
      "properties": {
        "my_field": {
          "type": "object",
          "additionalProperties": {
            "type": "object"
          }
          "x-go-name": "MyField"
        }
      }
    }
  }
}
```

`interface{}` as value in a `map` should be mapped to `any`. This PR fixes this! 

the problem is more described in: #2758

2022-05-22 17:46 UTC, casualjim commented
I don't think this PR fixes #2758 

As far as I can tell this PR just removes the default of type: object to be any type of json value.  But it doesn't address the real issue that is mentioned which is respecting `swagger:type`

2022-05-22 17:46 UTC, casualjim requested changes
Are you going to work on supporting `swagger:type`

2022-05-22 19:25 UTC, emilgpa commented
@casualjim Yes, you're right. It is also related to `swagger:type`. Although I understand from the code that `swagger:type object` doesn't exist. Could that be the reason the guy was trying to use it to avoid the `additionalProperties` generated by `interface{}`?. Anyway, i included in the PR support `swagger:type object` (it did not exists).

2022-05-23 16:28 UTC, casualjim approved these changes

2022-05-23 16:28 UTC, merged