fixes #2831, circular dependency issue
go-swagger/go-swagger pull request #2832
Opened 2022-09-08 21:20 UTC by Aven30

2022-09-08 21:23 UTC, Aven30 commented
My approach was to track what schemas, based off of location, has already been compared. This  makes it where we can complete the DIFF on a specs that have circular references as expected.

2022-09-08 22:19 UTC, casualjim requested changes

2022-09-08 22:19 UTC, casualjim commented on fixtures/diff/refcircular.v2.json
> +        "id": { "type": "integer" },`
That ` should not be there

2022-09-09 18:17 UTC, Aven30 commented
Gahh, my bad, removed!

2022-09-09 20:22 UTC, casualjim approved these changes

2022-09-09 22:15 UTC, merged